print ("Enter two numbers")
print ("Enter the first number")
num1 = int (input())
print ("Enter the second number")
num2 = int (input())
print ("Addition of two numbers",num1 + num2)
print ("Subtraction of two numbers",num1 - num2)
print ("Multiplication of two numbers",num1 * num2)
print ("Division of two numbers",num1 / num2)